# Generated by Django 3.0.2 on 2020-02-02 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Areas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_paso', models.SmallIntegerField()),
                ('nombre', models.CharField(max_length=40, verbose_name='nombre del paso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pasos',
                'ordering': ['id_reporte', 'n_paso'],
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('servidor', models.IntegerField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='ip del servidor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Servidores',
                'ordering': ['servidor'],
            },
        ),
        migrations.CreateModel(
            name='TipoFuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30, verbose_name='tipo de fuente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de fuentes',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='TipoPaso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='tipo de paso')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docs.Area')),
            ],
            options={
                'verbose_name_plural': 'Solicitantes',
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='RequisitoPaso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fuente', models.CharField(max_length=50, verbose_name='nombre tabla fuente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.Paso')),
                ('tipo_fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docs.TipoFuente')),
            ],
            options={
                'verbose_name_plural': 'Requisitos de paso',
                'ordering': ['id', 'id_paso'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('prioridad', models.IntegerField(choices=[(0, 'Urgente'), (1, 'Importante'), (2, 'Media'), (3, 'Baja')], default=2)),
                ('hora_actualizacion', models.TimeField(verbose_name='hora de actualización')),
                ('repeticion', models.SmallIntegerField(blank=True, null=True, verbose_name='tiempo de repetición')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dias', models.ManyToManyField(to='docs.Dia', verbose_name='dias de actualización')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docs.Servidor')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docs.Solicitante')),
            ],
            options={
                'verbose_name_plural': 'Reportes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='paso',
            name='id_reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.Reporte'),
        ),
        migrations.AddField(
            model_name='paso',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docs.Servidor'),
        ),
        migrations.AddField(
            model_name='paso',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docs.TipoPaso', verbose_name='tipo de paso'),
        ),
        migrations.AlterUniqueTogether(
            name='paso',
            unique_together={('n_paso', 'id_reporte')},
        ),
    ]
